export const FakePlacesData = [
  {
    id: 1,
    image: 'https://source.unsplash.com/random?sig=1',
    name: 'Timgad',
    review: 4.5,
    wilaya: 'Batna',
    distance: 390,
  },
  {
    id: 2,
    image: 'https://source.unsplash.com/random?sig=2',
    name: 'Rmiliya',
    review: 4,
    wilaya: 'Chlef',
    distance: 242,
  },
  {
    id: 3,
    image: 'https://source.unsplash.com/random?sig=3',
    name: 'Hoggar Mountains',
    review: 4.8,
    wilaya: 'Tamanrasset',
    distance: 1200,
  },
  {
    id: 4,
    image: 'https://source.unsplash.com/random?sig=4',
    name: "Tassili n'Ajjer",
    review: 4.7,
    wilaya: 'Illizi',
    distance: 880,
  },
  {
    id: 5,
    image: 'https://source.unsplash.com/random?sig=5',
    name: 'Casbah of Algiers',
    review: 4.6,
    wilaya: 'Algiers',
    distance: 15,
  },
  // {
  //   id: 6,
  //   image: 'https://source.unsplash.com/random?sig=6',
  //   name: 'Djemila',
  //   review: 4.4,
  //   wilaya: 'Setif',
  //   distance: 220,
  // },
  // {
  //   id: 7,
  //   image: 'https://source.unsplash.com/random?sig=7',
  //   name: "M'zab Valley",
  //   review: 4.9,
  //   wilaya: 'Ghardaia',
  //   distance: 600,
  // },
  // {
  //   id: 8,
  //   image: 'https://source.unsplash.com/random?sig=8',
  //   name: 'Sahara Desert',
  //   review: 4.7,
  //   wilaya: 'Multiple',
  //   distance: 1000,
  // },
  // {
  //   id: 9,
  //   image: 'https://source.unsplash.com/random?sig=9',
  //   name: 'Tlemcen',
  //   review: 4.3,
  //   wilaya: 'Tlemcen',
  //   distance: 160,
  // },
  // {
  //   id: 10,
  //   image: 'https://source.unsplash.com/random?sig=10',
  //   name: 'Annaba',
  //   review: 4.2,
  //   wilaya: 'Annaba',
  //   distance: 150,
  // },
]

export const FakeCategoriesData = [
  { id: 1, name: 'Mountains' },
  { id: 2, name: 'Beaches' },
  { id: 3, name: 'Forests' },
  { id: 4, name: 'Deserts' },
  { id: 5, name: 'Fields' },
  // { id: 6, name: 'Urban Skylines' },
  // { id: 7, name: 'Waterfalls' },
  // { id: 8, name: 'Lakes' },
  // { id: 9, name: 'Countryside' },
  // { id: 10, name: 'Islands' },
]
